Bookstore: add reducers and actions
manzitresor/book_store pull request #2
Opened 2023-07-17 20:49 UTC by manzitresor

### Implemented Feature

- [ ] Add Redux Toolkit
- [ ] Create a directory that will contain all your Redux logic
- [ ] Configure a Redux store
- [ ] Define a slice of state for books
- [ ] Define a slice of state for categories

2023-07-17 21:05 UTC, abdulhamiid requested changes
Hi @manzitresor 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request  ❌ ❌ ❌ 

- [ ] In your README, I noticed that the section `Future Features` is missing, please include 1-3 potential features to be added. 🤗

- [ ] For a descriptive readme, let's ensure that all main headers from the [README template](https://github.com/microverseinc/readme-template) are present in our repo.

* The only optional section is FAQ. ☺

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-17 22:35 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️ ♻️ ♻️

Hi @manzitresor,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✅ You used Gitflow correctly 👍🏽
✅ The Linter checks passed successfully 👍🏽
✅ Used Redux Toolkit as required 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-07-17 22:35 UTC, AmaduKamara commented on src/redux/store.js
> +export default store;
- [ ] Could you please use the book and category reducers in this file by importing them and using them in the reducer object as required?  You've already created them and using them here makes them available outside where you're using any of the actions 👍🏽

```jsx
import booksReducer from "./books/booksSlice"
import categoriesReducer from "./categories/categoriesSlice"

const store = configureStore({
  reducer: { books: booksReducer, categories: categoriesReducer },
})

export default store
```

2023-07-18 06:17 UTC, manzitresor commented
Hello @AmaduKamara for review feedback.
I'm working on it .

2023-07-18 06:26 UTC, topeogunleye approved these changes
### Hi @manzitresor, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Used the book and category reducers in this file by importing them and using them in the reducer object as required. ✔️
 
## [Optional] suggestions:
- For future pull requests, please notice that your branch name `reducer_and_actions` does not follow the convention of being named after a feature or action. For example, you could name your branch `added_reducer_and_actions`. This makes it easier to track the changes and the purpose of each branch. 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 09:03 UTC, merged